server:
  port: 8082

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/seed?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
