server:
  port: 8082
  servlet:
    session:
      cookie:
        domain: localhost
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/seed?characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/seed?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      connect-timeout: 5000
  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.topawar.manage.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-after-script: false


